/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.vasug

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.Task

/**
 * A simple 'hello world' plugin.
 */
class BuildTrackerPlugin implements Plugin<Project> {
    public static final String TASK_NAME = 'task-graph'

    void apply(Project project) {
        // Register a task
        project.gradle.addBuildListener(new TimeRecorder(this))

        project.allprojects { Project rootOrSubProject ->
            if (rootOrSubProject.tasks.findByName(TASK_NAME)) {
                // Skip if this sub-project already has our task. This can happen for example if the plugin is applied on allProjects.
                return
            }
            rootOrSubProject.tasks.register(TASK_NAME, TaskTreeTaskBase)

            rootOrSubProject.gradle.taskGraph.whenReady {
                if (project.gradle.taskGraph.allTasks.any { Task task -> task.class in TaskTreeTaskBase }) {
                    rootOrSubProject.tasks.configureEach { Task task ->
                        if (!(task in TaskTreeTaskBase)) {
                            task.setEnabled(false)
                        }
                    }
                }
            }
        }
    }
}
